locale.default: en # The default language if the player's language is not available on the server, or it has not been defined

first.join.message: true # A message when the player enters, telling about the definition of the player's language and the possibility of changing this language.
actionbar.indicators: true # Indicators above the player's toolbar. This function is needed for some plugins that use DarkWaterAPI. Requires PlaceHolderAPI to work.

rest.enable: false
rest.port: 8080
rest.name: darkwater

rest.auth.enable: true # Enable and disable authentication for Rest requests. If it is disabled, then some requests will be disabled.
rest.auth.type: BEARER # BEARER | BASIC

rest.bearer.expire: 744 # Token expire in hours
rest.bearer.secret: darkwater # Secret word for the HMAC256 algorithm when signing the token.
rest.bearer.users:
  - admin:admin # User:Password
  - darkwater:darkwater # User:Password

# To get a bearer token for a user, you need to send a no auth request to any Rest link.
# The request header must contain the 'user' and 'password' parameters.
# Attention: A token can only be obtained once per user.
# The next time the token can be obtained either after the end of the previous one, or after the plugin is reloaded.

rest.basic.login: darkwater
rest.basic.password: darkwater

rest.service.commands: true # Command Usage Service with REST
rest.service.code: true # Code generator for players when requested via REST

rest.encrypted.data: true # Accept encrypted data via REST or not

# Encrypted data REST: localhost:port/darkwater/code?uuid={ENCRYPTED Player name}&exponent={RSA Exponent}&modulus={RSA Modulus}
# Decrypted data REST: localhost:port/darkwater/code?uuid={Player name}&exponent={RSA Exponent}&modulus={RSA Modulus}
# This parameter applies to command and code services
# To get darkwater public key REST: localhost:port/darkwater/code || localhost:port/darkwater/execute



# ------------------- REST -------------------
# localhost:port/service name/ping?ip={IP} - View ping from the specified ip address to the server
# localhost:port/service name/data - Viewing Server Data
# localhost:port/service name/plugins - View all plugins
# localhost:port/service name/darkwater - View data of all plugins using DarkWaterAPI ***
# localhost:port/service name/execute?cmd={COMMAND} - Command usage ***
# localhost:port/service name/code?player={Player name}&exponent={RSA Exponent}&modulus={RSA Modulus} - Sends the code to the player, and also returns it in encrypted form ***
# localhost:port/service name/code?uuid={Player uuid}&exponent={RSA Exponent}&modulus={RSA Modulus} - Sends the code to the player, and also returns it in encrypted form ***
#---------------------------------------------
# You can also use instead of the player's name - his UUID
# *** - Disabled if REST authorization is disabled
# ------------------- REST -------------------




config.version: 2 # DO NOT TOUCH THIS PLEASE =)